### ISSUE TITLE
Add more maintainers?

### ISSUE THREAD

**Issue by NobodyXu** [ParkMyCar/compact_str#103]
I think it is unfair to put all the burden of maintaining this crate to @ParkMyCar .

Thus I propose that we should add a few new maintainers and perhaps also move this repository into an organisation.

I volunteer to be one and I will help review the PRs and answer issues.

**Comment by ParkMyCar** [comment]
I appreciate the concern! For now though I'd like to retain sole ownership. If this library every becomes more widely used, and there are so many changes that I cannot keep up, then we can revisit this 🙂
