### ISSUE TITLE
feature: truncate

### ISSUE THREAD

**Issue by Greatness7** [ParkMyCar/compact_str#131]
Great work on this library! So far substituting `String` with `CompactString` has given immediate performance improvements in the projects I've tested it on. 

The only unfortunate thing I ran into was that `CompactString` has no `truncate` method like that of `String`. Implementing it user-side is a bit scary because some `unsafe` is likely involved. Is there any chance it could be added in a future update?

Simple example using the `String` api:
```rs
    let mut s = String::from("Hello World!\n\n");
    assert!(s.len() == 14);
    
    s.truncate(s.trim_end().len());
    assert!(s.len() == 12);
```

**Comment by ParkMyCar** [comment]
Thanks for the issue @Greatness7 and @Kijewski for the implementation!
