### ISSUE TITLE
impl PartialEq<CompactStr> for &str

### ISSUE THREAD

**Issue by rusty-snake** [ParkMyCar/compact_str#14]
Example that works:
```rust
use compact_str::CompactStr;
fn main() {
    dbg!(CompactStr::from("hello") == "hello");
}
```

Example that don't work:
```rust
use compact_str::CompactStr;
fn main() {
    dbg!("hello" == CompactStr::from("hello"));  
}
```

Error:
```
error[E0277]: can't compare `&str` with `CompactStr`
 --> src/main.rs:4:18
  |
4 |     dbg!("hello" == CompactStr::from("hello"));
  |                  ^^ no implementation for `&str == CompactStr`
  |
  = help: the trait `PartialEq<CompactStr>` is not implemented for `&str`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `test01` due to previous error
```

I think it shouldn't make any differences whether you want to compare `&str` with `CompactStr`, `&str` with `&CompactStr`, `CompactStr` with `&str` or `&CompactStr` with `&str`.

**Comment by ParkMyCar** [comment]
Thanks for submitting the issue! I figured there would be a couple missing impls like this, I'll try and get this fixed soon. If someone else would like to submit a PR though, feel free 🙂
