### ISSUE TITLE
Support creating CompactString from &'static str in O(1)

### ISSUE THREAD

**Issue by NobodyXu** [ParkMyCar/compact_str#264]
I encounter several scenariors where I want to create a CompactString from &'static str and it would be great if that can be done in O(1) by simply storing a reference to the 'static str

**Comment by Kijewski** [comment]
I guess this is a special case of #223? I won't find the time to work on this PR in the foreseeable future, though.

**Comment by NobodyXu** [comment]
> I guess this is a special case of #223? I won't find the time to work on this PR in the foreseeable future, though.

Yeah, I would like to have something like:

    impl CompactString {
        fn from_static(s: &'static str) -> Self;
    }
    
I could try to implement this myself, though I am also a bit busy recently.
