### ISSUE TITLE
`ToCompactString` formats twice

### ISSUE THREAD

**Issue by GoldsteinE** [ParkMyCar/compact_str#269]
This test:

```rust
#[test]
fn to_compact_string_formats_once() {
    #[derive(Default)]
    struct FormatMeOnce(Cell<bool>);

    impl fmt::Display for FormatMeOnce {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            if self.0.replace(true) {
                panic!("formatted twice!")
            }

            f.write_str("FormatMeOnce")
        }
    }

    assert_eq!(FormatMeOnce::default().to_compact_string(), "FormatMeOnce");
}
```

fails. This problem occurs in practice with `Itertools::format()`, since formatting consumes the iterator, so trying to format it twice panics.

**Comment by GoldsteinE** [comment]
The same problem reproduces for `format_compact!()`.

**Comment by GoldsteinE** [comment]
That’s caused by this optimization:

https://github.com/ParkMyCar/compact_str/blob/9e00e7d6fcfd36a6f2608f3b09211128af10d64c/compact_str/src/traits.rs#L104

https://github.com/ParkMyCar/compact_str/blob/9e00e7d6fcfd36a6f2608f3b09211128af10d64c/compact_str/src/utility.rs#L6-L11

which looks sensible, but I think is incorrect to do for unknown types.

**Comment by NobodyXu** [comment]
Hmmm I am the one who wrote this and I never realized that this could happen.

I guess we can simply remove the `count(s)`, it would produce the correct behavior but less efficient for some types.

**Comment by GoldsteinE** [comment]
One alternative might be to specialize `count(s)` to do the optimization only for known-good types. The problem with that is that it’s impossible to do so for generic types like `Vec<T>` without true specialization.

**Comment by NobodyXu** [comment]
Yeah, we already contain enough specialisation for all primitive types, so it is probably enough.

**Comment by ParkMyCar** [comment]
Good find! I think the proposed fix to remove the call to `count(...)` is the right one, especially since we have optimizations for other primitive types, I'll put up a PR shortly
