### ISSUE TITLE
bug: Mutating underlying `&'static str`

### ISSUE THREAD

**Issue by ParkMyCar** [ParkMyCar/compact_str#313]
In the yet to be release API `CompactString::from_static_str`, you can create an instance of `CompactString`, backed by a `&'static str`. There are a few APIs on `CompactString` though that assume we own the underlying data, and thus modify it directly, e.g.

* [`retain()`](https://github.com/ParkMyCar/compact_str/blob/main/compact_str/src/lib.rs#L1206)
* [`drain()`](https://github.com/ParkMyCar/compact_str/blob/main/compact_str/src/lib.rs#L1110)
* [`insert_str()`](https://github.com/ParkMyCar/compact_str/blob/main/compact_str/src/lib.rs#L995)
* [`replace_range()`](https://github.com/ParkMyCar/compact_str/blob/main/compact_str/src/lib.rs#L844)

We need to fix these APIs to copy the underlying data before modifying it

**Comment by NobodyXu** [comment]
retain() should be ok, since it should invoke `as_mut_buf` which already handle this https://github.com/ParkMyCar/compact_str/blob/df20a0148ecd5df509f82a20b12c45f77a45471e/compact_str/src/repr/mod.rs#L497

**Comment by NobodyXu** [comment]
`drain()` also calls `as_mut_buf()`, so it should be ok.

**Comment by NobodyXu** [comment]
`insert()` calls `reserve()` which handles this, so it should be also ok.

**Comment by NobodyXu** [comment]
`replace_range*()` calls `as_mut_ptr()` or `reserve()` (in `replace_range_grow()`), so they should be ok.

**Comment by ParkMyCar** [comment]
@NobodyXu my bad 🤦‍♂️ you're totally right! I updated the branch that adds fuzz, will run it for a bit, and then release `v0.8.0-beta`!

**Comment by NobodyXu** [comment]
No worries!
Better to be careful than rush to fix the bug later.
