### ISSUE TITLE
Consider implementing From<CompactString> for std::error::Error

### ISSUE THREAD

**Issue by tylerhawkes** [ParkMyCar/compact_str#327]
I was using this today and mostly able to just add `use compact_str::CompactStr as String;` in the imports of any file where I wanted to convert to CompactString. A couple places needed some `.into()` to convert strings like from `serde_json`, so not a big deal. However, in one place I was returning `Result<(), Box<dyn std::error::Error>>` which for String converts with a `.into()` call, but not for `CompactString`. 

The std library does it [here](https://doc.rust-lang.org/stable/std/string/struct.String.html#impl-From%3CString%3E-for-Box%3Cdyn+Error+%2B+Sync+%2B+Send,+Global%3E).

There are several other `From` impls that could also be done as well if they're missing.

**Comment by Kijewski** [comment]
Sounds like a good idea. Maybe you could try to implement this conversion?

**Comment by tylerhawkes** [comment]
Ok, I'll try to make a PR for this.

**Comment by ParkMyCar** [comment]
Thanks for filing an issue @tylerhawkes! I love to see that we're getting closer to being a truly "drop-in" replacement for `String`. If you have the time to make a PR that would be great 😊
