### ISSUE TITLE
feature: easy integer to CompactStr

### ISSUE THREAD

**Issue by rusty-snake** [ParkMyCar/compact_str#82]
**TL;DR:** `1234.to_string()` but without heap allocation (and without `std::fmt`).

My use case are file-descriptor which I need to pass to a `Command` (and do other things with them before) so I need to have them as a `&str` instead of an `i32`/`RawFd`. It would be great if compact_str would support creation from an integer type (possible with [itoa](https://docs.rs/itoa/1.0.1/itoa/)).

If you think this does not match the goal of the project fell free to close.

**Comment by NobodyXu** [comment]
Checkout #16

**Comment by NobodyXu** [comment]
I have added int and float specialisation.

However, there is some strange bug for formatting float on target `powerpc64le`.
I tried disabling float spec and fallback to `Display` implementation, but the tests still failed for `ToCompactStr`.

@rusty-snake Can you please help me investigate the problem if you have time?

**Comment by NobodyXu** [comment]
@rusty-snake The PR #16  is merged.
